---
- hosts: lab_juniper_ro
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  - name:  Deploy NTP Server
    junos_install_config:
      host={{inventory_hostname}}
      user=aaron.paxson
      file=resources/config-user.set
      overwrite=false
      logfile=logs/deploy-user.log
