---
- name: run apt-get update
  apt: update_cache=yes

- name: install minimal toolset
  action: apt pkg={{item}} state=installed
  with_items:
        - git
        - bridge-utils
        - htop
        - tcpdump
        - telnet
        - curl

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh

- name: run docker hello 
  shell: docker run hello-world
  register: result

- debug: var=result

